name: Claude PR Auto Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Automatic PR Review
        uses: anthropics/claude-code-action@v1.0.2
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            請使用正體中文 zh-TW 進行所有回應，請先對本次 PR 進行一個簡單敘述，讓審查者快速理解本次是在調整甚麼東西，接著再進行後續的程式碼審查。
            
            Please review this pull request.

            Note: The PR branch is already checked out in the current working directory.

            Focus on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security implications
            - Test coverage
            - Documentation updates if needed
            - Verify that README.md and docs are updated for any new features or config changes

            Provide constructive feedback with specific suggestions for improvement.
            Use `gh pr comment:*` for top-level comments.
            Use `mcp__github_inline_comment__create_inline_comment` to highlight specific areas of concern.
            Only your GitHub comments that you post will be seen, so don't submit your review as a normal message, just as comments.
            If the PR has already been reviewed, or there are no noteworthy changes, don't post anything.

          claude_args: |
            --allowedTools "mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*), Bash(gh pr diff:*), Bash(gh pr view:*)"
